config/routes.rb
Rails.application.routes.draw do
  get 'login/index'

  post 'login/auth'

  resources :users
  resources :reviews
  resources :publishes
  resources :books do
    post 'search', on: :collection
  end

end

app/models/publish.rb
class Publish < ActiveRecord::Base
has_many :books
end

app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  before_action :set_publish, only: [:show, :edit, :update, :destroy]

  # GET /publishes
  # GET /publishes.json
  def index
    @publishes = Publish.all
  end

  # GET /publishes/1
  # GET /publishes/1.json
  def show
  end

  # GET /publishes/new
  def new
    @publish = Publish.new
  end

  # GET /publishes/1/edit
  def edit
  end

  # POST /publishes
  # POST /publishes.json
  def create
    @publish = Publish.new(publish_params)

    respond_to do |format|
      if @publish.save
        format.html { redirect_to @publish, notice: 'Publish was successfully created.' }
        format.json { render :show, status: :created, location: @publish }
      else
        format.html { render :new }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishes/1
  # PATCH/PUT /publishes/1.json
  def update
    respond_to do |format|
      if @publish.update(publish_params)
        format.html { redirect_to @publish, notice: 'Publish was successfully updated.' }
        format.json { render :show, status: :ok, location: @publish }
      else
        format.html { render :edit }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishes/1
  # DELETE /publishes/1.json
  def destroy
    @publish.destroy
    respond_to do |format|
      format.html { redirect_to publishes_url, notice: 'Publish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publish
      @publish = Publish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publish_params
      params.require(:publish).permit(:publishname, :address)
    end
end

app/helpers/publishes_helper.rb
module PublishesHelper
end

app/views/publishes/_form.html.erb
<%= form_for(@publish) do |f| %>
  <% if @publish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publish.errors.count, "error") %> prohibited this publish from being saved:</h2>

      <ul>
      <% @publish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publishname %><br>
    <%= f.text_field :publishname %><br>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.select :address, ["出雲市","松江市","テキサス州","ロンドン"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishes/edit.html.erb
<h1>Editing Publish</h1>

<%= render 'form' %>

<%= link_to 'Show', @publish %> |
<%= link_to 'Back', publishes_path %>

app/views/publishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publishes</h1>

<table>
  <thead>
    <tr>
      <th>Publishname</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishes.each do |publish| %>
      <tr>
        <td><%= publish.publishname %></td>
        <td><%= publish.address %></td>
        <td><%= link_to 'Show', publish %></td>
        <td><%= link_to 'Edit', edit_publish_path(publish) %></td>
        <td><%= link_to 'Destroy', publish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publish', new_publish_path %>

app/views/publishes/new.html.erb
<h1>New Publish</h1>

<%= render 'form' %>

<%= link_to 'Back', publishes_path %>

app/views/publishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publishname:</strong>
  <%= @publish.publishname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @publish.address %>
</p>

<%= link_to 'Edit', edit_publish_path(@publish) %> |
<%= link_to 'Back', publishes_path %>